index:
  path: /
  defaults: { controller: 'App\controller\IndexController::index' }
participant:
  path: /participant
  defaults:
    { controller: 'App\controller\ParticipantController::participantView' }
